# Generated by Django 2.1.4 on 2019-05-21 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('os_client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('cno', models.IntegerField(primary_key=30, serialize=False)),
                ('comment', models.CharField(max_length=30)),
                ('client_un', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_client.Client')),
            ],
        ),
    ]
