# Generated by Django 2.1.4 on 2019-05-21 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('os_client', '0001_initial'),
        ('os_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='property')),
                ('size', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('facing', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=30)),
                ('add_date', models.DateField()),
                ('sold_date', models.DateField()),
                ('agent_un', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_admin.AgentRegister')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyBlocked',
            fields=[
                ('bno', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('client_un', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_client.Client')),
                ('pno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_agent.Property')),
            ],
        ),
        migrations.CreateModel(
            name='SoldProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_sold', models.DateField()),
                ('client_un', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_client.Client')),
                ('pno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_agent.Property')),
            ],
        ),
    ]
